steps:

- name: 'gcr.io/cloud-builders/go'
  args: ['build', "-o", "packer-builder-arm-image"]
  env:
  - PROJECT_ROOT=github.com/solo-io/packer-builder-arm-image

- name: 'gcr.io/cloud-builders/go'
  args: ['build', "-o", "cmd/flasher/flasher", "github.com/solo-io/packer-builder-arm-image/cmd/flasher"]
  env:
  - PROJECT_ROOT=github.com/solo-io/packer-builder-arm-image

- name: 'gcr.io/$PROJECT_ID/go-make'
  entrypoint: ./hack/upload.sh
  secretEnv: ['GITHUB_TOKEN']
  env:
  - TAG_NAME=$TAG_NAME

secrets:
- kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQABlzmSQhtCq6661EaOys3Rz5P0/10ttglSaFN9lzaFCxnorASUQCCPGSGDE62fGJrtCucLxt29e1fTZtUCa0CqnwLi0xNNWiaNSRaYiazWMdwnUFO5wcMHz/7B+84tOzZZOVgh6iz2HoYy13b4iTmymj3xUsFRA==
